// leaves/src/examples/vue/fetch.vue
<template>
    <div class="fetch">
        <button @click="newItem">New quote</button>
        <p>{{ delta }}ms</p>
        <div>{{ currentItem }}</div>
    </div>
</template>

<script lang="ts">
export default {
    data() {
        return {
            currentItem: "",
            delta: 0,
        };
    },
    mounted() {
        this.newItem();
    },
    methods: {
        async newItem() {
            const tick = new Date().getTime();
            const items = await fetch("/api/fetch").then((r) => r.json());
            this.currentItem = items[Math.floor(Math.random() * items.length)];
            this.delta = new Date().getTime() - tick;
        },
    },
};
</script>

// leaves/src/examples/svelte/fetch.svelte
<script>
    import { onMount } from "svelte";
    let data = [];
    let currentItem = "";
    let delta = 0;
    const newItem = async () => {
        const tick = new Date().getTime();
        const data = await fetch("/api/fetch").then((r) => r.json());
        currentItem = data[Math.floor(Math.random() * data.length)];
        delta = new Date().getTime() - tick;
    };

    onMount(() => {
        newItem();
    });
</script>

<div class="fetch">
    <button on:click={newItem}>New quote</button>
    <p>{delta}ms</p>
    <div>{currentItem}</div>
</div>
